renamed to conform to google shell styleguide, simplify, added the rest of ship-it stuff to pushing and publishing release

diff --git a/git_tools b/git_tools
--- a/git_tools
+++ b/git_tools
@@ -3,25 +3,29 @@
 # Github and git helpers.
 # uses the variables set from gradle/build.yml
 # ------------------
+set -e  # Abort script at first error, when a command exits with non-zero status
 
+# defaults, this format says if GH_PAGES_DIR is not set then set it to these values
 : "${GH_PAGES_DIR:=build/gh-pages}"
 : "${GH_PAGES_BRANCH:=gh-pages}"
 
 # initialize variables for github
-# arg $1 - the GITHUB_FULLNAME in the format of owner/repo
-function initGithubVars {
+# will try and constuct GITHUB_FULLNAME from git config if not passed in
+# $1 - the GITHUB_FULLNAME in the format of owner/repo, if not passed in then it will constuct it
+function init_github_vars {
   local ghFullName="${1:-$GITHUB_FULLNAME}"
   if [ ! "$ghFullName" ]; then
     echo "GITHUB_FULLNAME not set, trying `git config --get remote.origin.url`"
     GITHUB_FULLNAME=$(git config --get remote.origin.url | cut -d/ -f4,5 | cut -d. -f1)
     # if it didn't get it then error
     [ ! "$GITHUB_FULLNAME" ] && echo "GITHUB_FULLNAME did not get setup" && return 1
+    ghFullName="$GITHUB_FULLNAME"
   fi
-  echo "initGithubVars with GITHUB_FULLNAME $GITHUB_FULLNAME"
+  echo "init_github_vars with GITHUB_FULLNAME $ghFullName"
   # keeps whats after last /
-  GITHUB_REPO=${GITHUB_FULLNAME##*/}
-  GITHUB_LINK_URL="https://github.com/${GITHUB_FULLNAME}"
-  GITHUB_BASE_URL="github.com/${GITHUB_FULLNAME}.git"
+  GITHUB_REPO=${ghFullName##*/}
+  GITHUB_LINK_URL="https://github.com/${ghFullName}"
+  GITHUB_BASE_URL="github.com/${ghFullName}.git"
   GITHUB_URL="https://$GITHUB_BASE_URL"
   echo "GITHUB_URL $GITHUB_URL"
   # For CI the git user token will be set in env var.
@@ -32,13 +36,13 @@ function initGithubVars {
   fi
 
   #echo "GITHUB_URL $GITHUB_URL"
-  verify-git-user
+  verify_git_user
 
   return 0
 }
 
 # checks is a git user is setup, and if not sets up the bot user, used in CI.
-function verify-git-user {
+function verify_git_user {
 
   local hasGitUser=$(git config --global user.email || true)
   # see https://stackoverflow.com/questions/3601515/how-to-check-if-a-variable-is-set-in-bash
@@ -52,23 +56,34 @@ function verify-git-user {
 }
 
 # shows the current git branch
-function current-git-branch {
+function current_git_branch {
   git rev-parse --abbrev-ref HEAD
 }
 
 # clones gh-pages into the build directory
-function git-clone-pages {
-  [ "$GITHUB_URL" ] || initGithubVars
+# $1 - GH_PAGES_BRANCH the branch, normally gh-pages
+# $2 - GH_PAGES_DIR the dir to clone it to, build/gh-pages
+# $3 - GITHUB_FULLNAME the full name
+function git_clone_pages {
+  local pagesBranch="${1:-$GH_PAGES_BRANCH}"
+  local pagesDir="${2:-$GH_PAGES_DIR}"
+  [ "$GITHUB_URL" ] || init_github_vars "$3"
   mkdir -p build
-  rm -rf $GH_PAGES_DIR
-  git clone $GITHUB_URL $GH_PAGES_DIR -b $GH_PAGES_BRANCH --single-branch --depth 1
+  rm -rf "$pagesDir"
+  git clone $GITHUB_URL "$pagesDir" -b "$pagesBranch" --single-branch --depth 1
 }
 
 # in build/gh-pages commits and pushes gh pages
-function git-push-pages {
-  git -C $GH_PAGES_DIR add -A .
-  git -C $GH_PAGES_DIR commit -a -m "CI Docs published [skip ci]" || true
-  git -C $GH_PAGES_DIR push -q $GITHUB_URL $GH_PAGES_BRANCH || true
+# $1 - GH_PAGES_BRANCH the branch, normally gh-pages
+# $2 - GH_PAGES_DIR the dir to clone it to, build/gh-pages
+# $3 - GITHUB_FULLNAME the full name
+function git_push_pages {
+  local pagesBranch="${1:-$GH_PAGES_BRANCH}"
+  local pagesDir="${2:-$GH_PAGES_DIR}"
+  [ "$GITHUB_URL" ] || init_github_vars "$3"
+  git -C $pagesDir add -A .
+  git -C $pagesDir commit -a -m "CI Docs published [skip ci]" || true # or true so doesnt blow error if no changes
+  git -C $pagesDir push -q $GITHUB_URL $pagesBranch || true
 }
 
 # sets up thee git user info for commit and push
@@ -85,8 +100,9 @@ function config_bot_user {
 
 # initializes a gh-pages branch for the first time
 # run this when setting up a new project's gh-pages
+# ! not fully tests so use it as a guide
 function init_gh_pages {
-  [ "$GITHUB_URL" ] || initGithubVars
+  [ "$GITHUB_URL" ] || init_github_vars
   mkdir -p build
   cd build
   rm -rf gh-pages
@@ -112,66 +128,27 @@ function git_push_tags {
   git push -q --tags $GITHUB_URL master
 }
 
-# updates the changelog
-# arg $1 - the LATEST_VERSION
-# arg $2 - the PREVIOUS_VERSION
-# arg $3 - the changelog filename
-function updateChangelog {
-  [ "$GITHUB_LINK_URL" ] || initGithubVars
-  # Repo URL to base links off of
-  local REPOSITORY_URL=$GITHUB_LINK_URL  #https://github.com/yakworks/gorm-tools
+# ---
+# checks a commit rangs to see if somethign other than docs has changed
+# $1 - the commit range like 911ff1ea1fa5...a883787c2f50
+# returns the list of file changes, empty if nothing
+# ---
+function hasAppChanges {
+  git diff $1 --name-status | grep -v -E "(README\.md|mkdocs\.yml|docs/)" || true
+}
 
-  # Get a list of all tags in reverse order
-  # Assumes the tags are in version format like v1.2.3
-  local GIT_TAGS=$(git tag -l --sort=-version:refname)
-  local TAGS=($GIT_TAGS)
-  # Make the tags an array
-  # TAGS=($GIT_TAGS)
-  local LATEST_TAG="v$1" # v6.1.12-v.1
-  local PREVIOUS_TAG="v$2" # v6.1.11-v.14
-
-  if [[ ! " ${TAGS[@]} " =~ " ${PREVIOUS_TAG} " ]]; then
-    echo "Error creating changelog - PREVIOUS_TAG $PREVIOUS_TAG does not exists"
-    return 1
-  fi
-
-  # We only get the commit hash so we don't have to deal with a bunch of ugly parsing
-  # See Pretty format placeholders at https://git-scm.com/docs/pretty-formats
-  local COMMITS=$(git log $PREVIOUS_TAG..HEAD --pretty=format:"%H")
-  # echo "COMMITS $COMMITS"
-  # Store our changelog in a variable to be saved to a file at the end
-  local MARKDOWN="#### $LATEST_TAG\n"
-  MARKDOWN+='\n'
-  MARKDOWN+="[Full Changelog]($REPOSITORY_URL/compare/$PREVIOUS_TAG...$LATEST_TAG)"
-
-  # Loop over each commit and look for merged pull requests
-  for COMMIT in $COMMITS; do
-    # Get the subject of the current commit
-    local SUBJECT=$(git log -1 ${COMMIT} --pretty=format:"%s")
-    # echo "SUBJECT $SUBJECT"
-    # If the subject contains [ci skip] then skip it
-    local PULL_REQUEST=$( grep -v -Eo "\[ci skip\]" <<< "$SUBJECT" )
-    if [[ $PULL_REQUEST ]]; then
-      # AUTHOR_NAME=$(git log -1 ${COMMIT} --pretty=format:"%an")
-      # AUTHOR_EMAIL=$(git log -1 ${COMMIT} --pretty=format:"%ae")
-
-      # Get the body of the commit
-      # BODY=$(git log -1 ${COMMIT} --pretty=format:"%b")
-      # echo "BODY $BODY"
-
-      MARKDOWN+='\n'
-      MARKDOWN+=" - $SUBJECT [$COMMIT]($REPOSITORY_URL/commit/$COMMIT)" # : $BODY"
-    fi
-  done
-  MARKDOWN+='\n'
-  echo -e "$MARKDOWN\n$(cat $3)" > $3
-  # Save our markdown to a file
-  #echo -e $MARKDOWN > CHANGELOG.md
+# ---
+# checks a commit rangs to see if docs have changed
+# $1 - the commit range like 911ff1ea1fa5...a883787c2f50
+# returns the list of file changes, empty if nothing
+# ---
+function hasDocChanges {
+  git diff $1 --name-status | grep -E "(README\.md|mkdocs\.yml|version.properties|docs/)" || true
 }
 
 #Just a helper to show variables which can be useful for debugging
 function git_debug {
-  [ "$GITHUB_URL" ] || initGithubVars
+  [ "$GITHUB_URL" ] || init_github_vars
   echo "GITHUB_FULLNAME: $GITHUB_FULLNAME"
   echo "GITHUB_BASE_URL: $GITHUB_BASE_URL"
   echo "GITHUB_URL: $GITHUB_URL"
